spring.application.name=movies
server.port=8080

# MySQL Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/moviesdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Anas@908070}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# OMDB API
omdb.api.key=${OMDB_API_KEY:YOUR_OMDB_API_KEY}
omdb.api.url=${OMDB_API_URL:http://www.omdbapi.com/}
